### ISSUE TITLE
caffe_unet was not found

### ISSUE THREAD

**Issue by bio-chris** [lmb-freiburg/Unet-Segmentation#17]
Hi, 

I am trying to run your U-Net plugin on our Linux server (Devuan GNU/Linux 2.0 , CUDA 9.2.88 and no CuDNN) and downloaded and installed the file caffe_unet_package_16.04_gpu_cuda9.tar.gz. When running caffe or caffe_unet on my commandline, everything seems to be fine. 

When trying to run the U-Net Job Manager and start a segmentation I get the following error message (up until then I was following your tutorial video)
![u-net_fiji_error](https://user-images.githubusercontent.com/32636474/52716047-31e5e900-2f9e-11e9-9c2c-43f8d3426890.jpg)

The caffe_unet binary file is however correctly located under /home/user/u-net/bin/. 

Any idea what the problem might be?

**Comment by ThorstenFalk** [comment]
Did you start Fiji from shell or via double-click from file browser? The double-click option does not load your .bashrc, so that PATH and LD_LIBRARY_PATH are not setup. If this is the case you have four options:

1. Start Fiji from the shell for which caffe and caffe_unet work
2. Set PATH and LD_LIBRARY_PATH global for local X sessions (For some window managers, adding a file `~/.profile` with content `. ~/.bashrc` is already sufficient). However, I cannot give clear instructions, because it depends on the used window manager
3. Write a small wrapper script to start Fiji that first sets up your paths and then calls the ImageJ-linux64 binary, and then double click this script instead of the ImageJ-linux64 binary.
4. Check "Use remote host", enter as hostname localhost and as credentials your username and password

**Comment by BolekZapiec** [comment]
I occasionally have the same issue (I think it's the same issue anyway) I also get the errors: 
Unknown command line flag 'sigint_effect' and "solver"
it seems that some instance of my Fiji issue the train command as "caffe train -solver...." where as others issue "caffe_unet train -solver...." (this one doesn't work)
I'm using different instances of Fiji as it seems when starting a train, all the images that are loaded have to be used as train or validate. 
Is this a version issue where the old unet plugin used "caffe_unet train" and the new one uses "caffe train" ?

**Comment by BolekZapiec** [comment]
In case it's not the LIBRARY path issue as Thorsten pointed out, I think I recall encountering this issue and had to fix it by issuing a: 
sudo apt-get remove caffe-tools-cuda

**Comment by bio-chris** [comment]
Many thanks Thorsten. I had indeed launched Fiji from the file browser. Running it from the shell solved all my problems.
