### ISSUE TITLE
Question: Fine tuning in AWS spends hours uploading files

### ISSUE THREAD

**Issue by xun468** [lmb-freiburg/Unet-Segmentation#31]
Is this expected behavior? I have 10 annotated images and wanted to use 3 for validation, however I waited 4 hours and the unet plug-in was still uploading files to AWS. Is this expected behavior?

**Comment by ThorstenFalk** [comment]
Hi xun468,

I assume you used a very small tile size, so that ten thousands of tiles were generated with almost 100% overlap. I'd recommend to increase the tile size to reduce the overhead for overlap regions which will also dramatically reduce the total amount of data that must be transfered (and the number of files).

**Comment by aashrithSaraswathibhatla** [comment]
Hey Xun, 
Can you share more details about your AWS specifics? I am new to AWS and having troubles running the plugin with AWS. I am looking for instance specifics.
Thanks,
Aashrith

**Comment by xun468** [comment]
Sorry to necro this so late, what tile size would you recommend for images that are 1600x1200 where one pixel is about 1 micrometer?

**Comment by ThorstenFalk** [comment]
It depends on your GPU. The plugin gives a rough estimate on the required GPU memory when you change the tile size. I recommend to adjust the tile size to use all available GPU memory (-10% due to possible estimation inaccuracies). So if you use cuDNN and have 6GB of GPU memory (or you have no cuDNN but 12GB of GPU memory) I'd recommend

![Tilesize](https://user-images.githubusercontent.com/25524869/56883565-5ca4f100-6a67-11e9-9c7a-3c89b68de7c9.png)

This will produce output tiles of size 468x468 and thus 4x3 = 12 tiles per image.
