### ISSUE TITLE
Post Unet update - local execution broken - caffe_unet not found

### ISSUE THREAD

**Issue by BolekZapiec** [lmb-freiburg/Unet-Segmentation#44]
I updated the unet plugin on the local installation of fiji on my ubuntu server to address the bug where command line execution ignored the model/weights parameters. Unfortunately the new version results in segmentation not running at all. Remote execution from a windows machine with the old plugin still woks fine - I've yet to update it to test if it breaks it too. 

Following the update, running a segmentation job from the GUI plugin results in "Caffe_unet was not found, please specify your caffe_unet binary" message. This is not the library issue as the command caffe_unet executes both remotely via SSH, and locally via terminal. When I execute it locally I can't get it to work but if connect to caffe_unet via SSH - the segmentation job executes fine. 

I've tried restarting and deleting IJ_prefs in ~/.imagej/ - no joy. 

Executing the segmentation job via a macro results in a more informative error: 
Caffe blobs saved to '/home/administrator/cellnet/unet-9f09797f-9c1b-482f-8e8e-48520e2613ce.h5'
caffe_unet tiled_predict -infileH5 /home/administrator/cellnet/unet-9f09797f-9c1b-482f-8e8e-48520e2613ce.h5 -outfileH5 /home/administrator/cellnet/unet-9f09797f-9c1b-482f-8e8e-48520e2613ce.h5 -model /home/administrator/Desktop/CPbolek/UNET/caffemodels/OE4chanDAPI1_23JUN19.modeldef.h5 -weights /home/administrator/cellnet/caffemodels/OE4chanDAPI1_23JUN19.caffemodel.h5 -iterations 0 -tile_size 1188x1188 -gpu 1 
caffe_unet: symbol lookup error: caffe_unet: undefined symbol: _ZN5caffe3NetIfE21CopyTrainedLayersFromERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

**Comment by ThorstenFalk** [comment]
Undefined symbols are definitively a library issue and unrelated to the plugin update. It will definitively work using ssh both locally and remotely.

Starting caffe_unet from your ImageJ obviously uses the wrong libcaffe.so. You must have another caffe installation shadowing the libcaffe.so belonging to caffe_unet. Since caffe_unet successfully runs from command line, I assume that you properly setup .profile and .bashrc. So the only possible reason for plugin failure is that .profile and .bashrc were never executed in the environment ImageJ was started in, e.g. starting ImageJ via double-click from a file manager bypasses .profile and the like.

Do you observe the same behavior when starting ImageJ from the terminal in which caffe_unet executed fine?

**Comment by BolekZapiec** [comment]
As usual, you're absolutely right. It just happened that I had added Fiji to my dash recently and hadn't relaunched Fiji since until yesterday's update - by when I had forgotten about the dash change. Launching as normal works fine - it was just the dock/dash shortcut that bypassed the library reference - Sorry about that!
