### ISSUE TITLE
How can I train datasets like PASCAL VOC without fiji?

### ISSUE THREAD

**Issue by JimHeo** [lmb-freiburg/Unet-Segmentation#50]
Hi there!

I just wanna train datasets for segmentation using only caffe. (without fiji)
But, I can't understand attributes of blobs like HDF5 training file.
When I use fji to do 'U-Net -> Utilities -> Creat Blobs', then I can make HDF5 file which contains data, labels, weights, weights2, __DATA_TYPES__, conversionParameters.
I'm trying to write some scripts to make that HDF5 file using python but I'm not sure I can do that...
Is there way to do that without GUI?

Regards,
Jim

**Comment by ThorstenFalk** [comment]
Hi Jim,

U-Net can in principle be used for natural images like PASCAL VOC and the like but there are much better models around. I would definitely first check the literature for alternatives with existing comparisons to (vanilla) U-Net.

If you have MATLAB you can use the MATLAB scripts in [U-Net: Convolutional Networks for Biomedical Image Segmentation](https://lmb.informatik.uni-freiburg.de/people/ronneber/u-net/) to generate the blobs including augmentation.

However, most of the augmentations are not very useful for natural images, e.g. compared to microscopic images image orientation is an important cue for natural images. Also local image deformations are most often harmful. You also encounter scale variations due to the perspective camera, self-occlusion and object cropping at the image boundaries. A mirroring across the boundaries as was done or the EM recordings does not work for natural images.

So if you want to use U-Net, pad out-of-image regions with a special value e.g. zero, turn off elastic deformation and rotation. Instead add RGB augmentations, like white-point shifts and Poisson/Gaussian noise augmentation. The receptive field of the vanilla U-Net with four resolution levels is approximately 184x184 pixels, objects exceeding this size especially if they do not show some characteristic texture will not be properly segmented. So you have to play with the number of resolution levels and with more classes more feature channels in the decoder may be required.

All the best,

Thorsten

**Comment by JimHeo** [comment]
Hi Thorsten,

I had the vacation. Sorry for the late reply.
I understand that natural images are not proper to use U-Net.
But also, I want to try to train CT image dataset.

I'm new to MATLAB or JAVA, so it is too hard to understand some scripts...
![unet_log](https://user-images.githubusercontent.com/26153903/62590942-f1da4000-b908-11e9-9b43-ad57e0de0e02.png)
I want to following this process to use command line...
but when I opened the unet-aa001d20-679f-491a-a96c-c245afc37e0b_train_0.h5,
there are groups like `__DATA_TYPES__`, `conversionParameters` and some datum like `data`, `labels`, `weights`, `weights2` which have attributes.
I'm just wandering that inside of HDF5 file, especially, `weights` and `weights2`.
I guess the one is the output using connected component labeling, but I don't know about the other one.
![Screenshot from 2019-08-07 12-01-31](https://user-images.githubusercontent.com/26153903/62591616-28b15580-b90b-11e9-9de8-0b13135495b9.png)
In this picture, the input of createDeformation layer is `weights2`...
I think `weights` and `weights2` are for augmentataion...but not exactly...
So, would you explain that...?
I really appreciate it alot.

Regards, 
Jim

**Comment by ThorstenFalk** [comment]
weights are for class weighting and extra-weights on instance boundaries for instance segmentation, weights2 are the pdf from which the center point of input patches is sampled. Please read the supplements of our Nature methods paper for details.

**Comment by JimHeo** [comment]
I missed that supplements,,,
Appreciate it!
