### ISSUE TITLE
caffe_unet not found

### ISSUE THREAD

**Issue by ashley-williams** [lmb-freiburg/Unet-Segmentation#51]
Hi All,

I was trying to install and follow the tutorial for segmentation. I have POP! OS 19.04 with the frontend and backend running on the same machine. I followed the instructions on the project page to install u-net from pre-built binaries, except that I did not install CUDA as I have already installed CUDA 10.0 in lib/CUDA-10.0. I tried to set up the environment with the following lines:

```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/cuda-10.0/lib64/
export UNET_PATH="$/home/username/u-net"
export PATH="$PATH:$/home/username/u-net/bin"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$/home/username/u-net/lib:/home/username/u-net/extlib"
```

I tested it by simply typing caffe on the terminal and that works. 
testing caffe_unet results in command not found. 

I ran U-net Segmentation on ImageJ and the error "caffe_unet was not found" came out. As I saw the same question raised by Christian on another thread (#17), I opened imageJ from the shell.
But it still doesn't work. 

I know very little about linux and would really appreciate some suggestions on how to fix this issue. 

Thank you!

**Comment by ThorstenFalk** [comment]
Hi Ashley,

Your description indicates that you have at least two issues:

1. Your system already contains an installation of caffe (probably via your package management system). That's why you find caffe but not caffe_unet. You can easily verify that this is the case by typing
````
which caffe
````
into a terminal. I expect that you will get something similar to /usr/bin/caffe, but it should be /home/username/u-net/bin/caffe. The main problem is, that, even if your paths are setup properly, you will run into library hell, because you also have two different versions of the shared library libcaffe.so.0.

2. Your settings for PATH and LD_LIBRARY_PATH were not loaded by the shell (verify with
````
echo $PATH
````
and
````
echo $LD_LIBRARY_PATH
````
. Both are probably missing your path to caffe_unet. This can have two reasons: 1. You do not use bash as shell (check with
````
echo $SHELL
````
), so .bashrc is not loaded or you have no .profile file sourcing .bashrc (check with ````cat ~/.profile````) If you get "file not found" create a new .profile with contents
````
. ~/.bashrc
````
then your .bashrc should be automatically loaded with the next terminal you open.

**Comment by ashley-williams** [comment]
I tried `sudo apt-get remove caffe-tools-cuda` and that worked. I checked your above commands and they are all showing the path to unet. Thank you for your help!

**Comment by ashley-williams** [comment]
I thought that worked, then I tried to do some fine tuning and I am getting the error again. Could you please advise? 
`caffe` and `caffe_unet` both work.

**Comment by ThorstenFalk** [comment]
This is certainly possible, but the procedure depends on your window manager. For KDE you might find the solution in [this KDE userbase article](https://userbase.kde.org/Session_Environment_Variables). In Unity you may try setting the environment in ~/.xsessionrc (see [Question on askubuntu.com](https://askubuntu.com/questions/82120/how-do-i-set-an-environment-variable-in-a-unity-session)). For other window managers check corresponding documentation.

**Comment by ThorstenFalk** [comment]
You probably use gnome, maybe adding the entries to ~/.pam_environment might work in your case. But be careful, the syntax is different and if you accidentally replace the PATH instead of appending to the current path you may not be able to login any more with X. In this case login to a tty and remove the file ~/.pam_environment [see this nice overview](https://help.ubuntu.com/community/EnvironmentVariables).
