### ISSUE TITLE
custom commands backend server after ssh

### ISSUE THREAD

**Issue by pr4deepr** [lmb-freiburg/Unet-Segmentation#55]
Hi 
  Thanks for this great plugin. I have managed to get our institute to install caffe_unet  on their cluster. It is available as a singularity container and it needs to be loaded first before running caffe_unet. 
Is there an option of running custom commands from FIJI after connecting to the remote host? In this case, i would like to run module load caffe_unet/18.04 before the UNET plugin calls caffe_unet?
Also, it may be handy to have the option to run other commands as well.

Thanks
Pradeep

**Comment by ThorstenFalk** [comment]
Hi Pradeep,

I added a custom command field to the Dialogs, but they are not yet recordable. I will add this when I find the time.

All the best,

Thorsten

**Comment by pr4deepr** [comment]
Hi Thorsten
  Thanks for this. Appreciate the quick turnaround.
Appreciate the extra info when hovering the mouse on it
Cheers
Pradeep

**Comment by pr4deepr** [comment]
The log window with the commands do not appear either..

**Comment by ThorstenFalk** [comment]
Oh, OK, maybe I missed a caveat.

**Comment by ThorstenFalk** [comment]
I don't actually see which caveat I missed, but added a guard to avoid null references or empty commands. startupCommands are now also recorded by the macro recorder and can be replayed.

**Comment by pr4deepr** [comment]
Hi
 Thanks a lot for this. Its working now. 
To clarify, can the commands in the startupcommand box still be executed, if I have not ticked Use remote host? Say, if I am running a desktop session on a cluster and would like to load modules on the cluster from within FIJI, rather than loading them before I run FIJI, can I still use this box?

Cheers
Pradeep

**Comment by ThorstenFalk** [comment]
Hi Pradeep,

the current implementation only works in SSH remote mode. It is in 
principle not hard to do the same for local calls, but I did not 
implement it, yet. It is anyways not a big deal, because if you already 
have an interactive session, you can easily setup everything before 
starting Fiji (even automatically with a script if you want to).

Getting commands over SSH was high priority, because it was a blocker, 
but adding this functionality also for local usage is only convenience, 
and thus has low priority. I will look into it, when I find some time.

All the best,

Thorsten

**Comment by pr4deepr** [comment]
Thanks Thorsten
 I completely understand. 
We have been having issues with our servers, so its taking some time to test it out. 
Appreciate the timely responses and advice!
