### ISSUE TITLE
Caffe installation help - please :)

### ISSUE THREAD

**Issue by ealemany** [lmb-freiburg/Unet-Segmentation#58]
Greetings,

I am a sys admin for the Dept of Radiation Oncology and i have been asked to help install Caffe.
However, I am in no way an expert in using CUDA - I have installed CUDA 10 on ubuntu servers on several occasions. The rest of the config (libraries, software etc...) usually the post-docs take care it. But the post-docs is running into some issue and asked me if i could help
I followed the instructions at 
https://lmb.informatik.uni-freiburg.de/resources/opensource/unet/#installation

But i have to be honest with you that i am at lost and confused. There are error messages when i ran the "cmake" command 
"CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version"
"-- Could NOT find GFlags (missing: GFLAGS_INCLUDE_DIR GFLAGS_LIBRARY) 
-- Could NOT find Glog (missing: GLOG_INCLUDE_DIR GLOG_LIBRARY) 
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Protobuf (missing: Protobuf_INCLUDE_DIR)" 

etc.....

If someone could have the patience to walk me through the process I would greatly appreciate it.

I have one server that i can experiment with. The specs are as followed:
Ubuntu server 16.04
Nvidia 440.33.01
CUDA 10.2
2 GeForce GTX 1080

Again, thank you very much for your help. I hope this is the right place to ask for help.

Best,
Eric

**Comment by ThorstenFalk** [comment]
You mention cmake, so I assume you want to build caffe_unet from scratch. That's in principle a good idea because no binary package perfectly matches your environment.

However, I am not sure whether your environment is supported at all...

You are running Ubuntu 16.04. I remember that it was a bit painful to build caffe with latest cuda on 16.04. The Ubuntu 16.04 cmake version is too old, so I had to download a new one and build it from scratch before I could even start.

Anyways this is not yet the problem you encountered. The reported errors indicate that prerequisites are missing. Did you run the

apt get install -y wget git unzip build-essential cmake libboost-system-dev libboost-thread-dev libboost-filesystem-dev libprotobuf-dev protobuf-compiler libhdf5-serial-dev libatlas-base-dev libgoogle-glog-dev

line before you started the installation? Then everything should be found automatically.

**Comment by ealemany** [comment]
Sorry for the delay in responding and Thank you for your help.  I ran the prerequisites and they were already installed.

"0 upgraded, 0 newly installed, 0 to remove and 14 not upgraded"

By the way cmake version was  3.5.1-1ubuntu3. I downloaded and install cmake 3.17.0-rcl
I also had to install the latest OpenSSL development tool.

So now i am ready to configre and build caffe_unet. On the website it shows an example 

"cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/unetuser/u-net -DUSE_OPENCV=OFF -DUSE_LEVELDB=OFF -DUSE_LMDB=OFF -DBUILD_python=OFF -DBUILD_python_layer=OFF -DCUDA_ARCH_NAME=Manual -DCUDA_ARCH_BIN="20 30 35 50 60 61" -DCUDA_ARCH_PTX="35" .."

but these are not the  options that match the compute capability of my GPU.

What do i need to change in order to match the compute capability of my GPU?
Is there a generic build i can use?

Here are the specs of the GPU:
Nvidia 440.33.01
CUDA 10.2
2 GeForce GTX 1080

I thank you in advance again for your help.

Best,
Eric

**Comment by pr4deepr** [comment]
@ThorstenFalk , correct me if I am wrong, 
I think you change the last bit of the code: 
 -DCUDA_ARCH_PTX="35" .."
to match the compute capability of your GPU
You GPU is GTX1080, so as per the NVIDIA website
https://developer.nvidia.com/cuda-gpus   & 
https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/
compute= 6.1, so it will be
 -DCUDA_ARCH_PTX="61" .."
So, 
"cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/unetuser/u-net -DUSE_OPENCV=OFF -DUSE_LEVELDB=OFF -DUSE_LMDB=OFF -DBUILD_python=OFF -DBUILD_python_layer=OFF -DCUDA_ARCH_NAME=Manual -DCUDA_ARCH_BIN="20 30 35 50 60 61" -DCUDA_ARCH_PTX="61" .."

Let me know if this works.

**Comment by ealemany** [comment]
@pr4deepr , Thank you for your help. I followed your instructions and all seemed to be installed correctly.
One thing thought, in the output i noticed that it says:

"CMake Warning at cmake/Dependencies.cmake:90 (message):
  -- CUDA is not detected by cmake.  Building without it..."

What does that mean exactly ?
Does that mean I cannot use the GPU?

Thank you @pr4deepr and @ThorstenFalk for your help in this project.

**Comment by ThorstenFalk** [comment]
If CUDA is not found GPU support will be disabled. You probably installed CUDA toolkit to a non-standard location. Then you need to additionally provide the path to your CUDA installation to cmake via -DCUDA_TOOLKIT_ROOT_DIR=/path/to/your/cuda/installation

If that folder also contains cuDNN, it might be found automatically, otherwise you have to also provide the path explicitly. Try to use ccmake to configure caffe_unet interactively, then you will see which variables need to be set.

**Comment by ealemany** [comment]
@ThorstenFalk , Thank you for the tip. I was able to locate CUDA - /usr/loca/cuda-9.2
I ran the command again including -DCUDA_TOOLKIT_ROOT_DIR=/usr/loca/cuda-9.2
and it found it -- CUDA detected: 9.2

when you say "Try to use ccmake to configure caffe_unet interactively, then you will see which variables need to be set."  How do you do that exactly?

Thanks

**Comment by ThorstenFalk** [comment]
You can use ccmake exactly as you use cmake, but instead of configuring the project from the provided parameters it will show you an interactive ncurses gui, that lists all available build parameters and you can set them interactively.

Just run
```
ccmake ..
```
you can add all parameters as before if you want to, then all provided fields will be set to the given values. Then hit "c" to do an initial configuration step. Thereafter the list with parameters should appear (in case of warnings/errors you have to hit "e" before, but ccmake will tell you). New parameters will be marked with an asterisk (*). xxx_NOT_FOUND indicates that cmake could not find the corresponding setting automatically. In most cases this is not critical. If you hit "t" in the list you toggle to the full list of available parameters. After setting parameters you have to hit "c" again to reconfigure. Maybe new options pop up. Repeat these steps until no rows are marked with * and hit g to finally generate the Makefile. Then you're done and can continue as after the normal cmake step.

**Comment by ealemany** [comment]
@ThorstenFalk, Thank you for such great detailed steps. I will definitely document this for the next server we will install and configure Caffe. 
I did the install on a ubuntu 16.04 server with the  GeForce GTX 1080 GPU. The post-doc (currently out sick) will try the server and if all good then I will do the install on a ubuntu 18.04 server with Tesla V100.

I truly appreciate your help in this project and I want to thank you again for the time you took to explain everything.
