### ISSUE TITLE
Install and run Unet-Segmentation from Windows

### ISSUE THREAD

**Issue by PaulineBlz** [lmb-freiburg/Unet-Segmentation#64]
Hello,

I want to install the backend and frontend of Unet-Segmentation on the same machine with Windows 10 as OS ( I do not have access to a server with Linux and I tried a virtual machine but cannot use the GPU in this VM).

What I tried so far is to "manually" download CUDA toolkit and caffe_unet_package_16.04_gpu_no_cuDNN.zip.

I have followed the instructions from Setup on own server (using pre-built binaries) in https://lmb.informatik.uni-freiburg.de/resources/opensource/unet/

So, after downloading and extracting the files, I went to System properties --> Advanced --> Environment Variables to edit the paths.
I created a LD_LIBRARY_PATH variable and add the three paths requires (cuda lib, u-net lib and u-net extlib) and I added to my Path variable the u-net bin path.

Hence, when I run the plugin on Fiji, I have still the issue "caffe u-net was not found". 

Do you have solution to perform the installation well on Windows ?

Thanks for your time,

Sincerely.

**Comment by ThorstenFalk** [comment]
I am very sorry, but backend installation on Windows is not supported. The binaries will only run on Linux given all third-party dependencies are met.

Running the backend in a virtual machine with GPU support is not (easily) possible as you already found out. The virtual machine needs exclusive access to your GPU which is not possible if Windows uses the same GPU for screen rendering. If you have multiple GPUs there is a quite theoretical option to entirely blacklist the GPU for Windows and pass it exclusively to the virtual machine, but it's more like a rumour in a forum that this works. I never heard someone really getting it running this way.

Another theoretical option would be to build caffe-unet on Windows, install an openssh server on your windows machine and then connect with the plugin, but installing the third-party dependencies for caffe-unet is already tricky, then you need a proper toolchain like Visual C++ or mingw64 to compile the backend and finally you will have to slightly patch the U-Net segmentation plugin to allow non-posix signal handling.

If you understood everything I just wrote and already have experience with compiling Windows software on your own, you might have a chance to get it running otherwise try to get hands on a physical computer running Ubuntu or a corresponding rented AWS instance and use the Linux binaries.

**Comment by PaulineBlz** [comment]
Hey,

Thank you for the fast reply ! 
I will investigate the option to build caffe-unet on Windows but I think at the end I'll probably directly switch to Ubuntu :)

**Comment by PaulineBlz** [comment]
Hello back,

So I did not manage to make it work on Windows but I have tried to install the CPU only version of caffe unet on my Linux virtual machine.
When I run the plugin in Fiji (from the shell) I get the same error message as caffe_unet not found but now it only said "caffe not found".

Do you have an idea about where the problem can comes from ?

Thanks !

**Comment by ThorstenFalk** [comment]
Do you have another version of caffe installed? E.g. the ubuntu caffe? If so, libcaffe.so of the Ubuntu version will be accidentally used instead of the one shipped with caffe_unet. Try apt-get remove caffe

**Comment by PaulineBlz** [comment]
Hey,

It works ! Thank you very much for the help.
