### ISSUE TITLE
U-net installation

### ISSUE THREAD

**Issue by ssg5** [lmb-freiburg/Unet-Segmentation#84]
Hello, 
I am an experimental material engineer and I am quite new to programming. Recently the project I am working on needs image processing and segmentation. After much literature survey, I found U-net plugin would be perfect for me to segment my images. But I am stuck with the installation of the backend server, I have consulted multiple people, but I was unsuccessful in the installation. I would really appreciate it if someone could help me out. 
Thanks a lot.

**Comment by Hir320** [comment]
Hello,

I am also a beginner of programming. But I might be able to tell you something. Would you state which OS and CUDA you are using, and what made you stacked?

**Comment by ssg5** [comment]
Hello, Thanks a lot for responding. I am trying to install the backend server on ubuntu 18.04 which is on a virtual GPU (oracle) on a windows computer. I have tried installing the backend server using the pre-built binaries and from the source. I am using CUDA 10.1. When I try to test "caffe" command, it shows me an error and when i try to test "caffe_unet" i get a usage message. Then when i try to execute the "ssh localhost caffe_unet" command, I get a usage message. 
When i check if you can connect to the server and execute a program there i get errors telling "connection refused". I tried resolving that but it doesn't connect to the server whatsoever.
Sorry if some of it doesn't make sense, I am not sure if I am using the correct way to describe. 
Could you please help me out. I can reach out to you via mail as well if that is more convenient. TThanks a lot I look forward to hearing from you.

**Comment by ssg5** [comment]
When i tried to check what kind of GPU, I found out my GPU 0 is Intel (R) UHD Graphics 630 with a GPU memory of 15.9 GB. and I have a CPU. So I tried installing the caffe_unet_package_18.04_cpu.tar.gz  and then followed the steps listed from Installation of the U-net package in "setup on own server (using pre-built binaries)" as I don't need to install CUDA. I think this is right, please let me know?

**Comment by Hir320** [comment]
Sorry. It seems your environment is too complex for beginners including me. I can only tell you that the best environment for U-Net is a computer with a real GPU such as RTX2080Ti, CUDA 10.0, and Ubuntu 18.04. 

Sorry, but I do not have experiences with virtual GPUs.

**Comment by ThorstenFalk** [comment]
Your setup seems to be quite special. I especially wonder how an intel GPU and CUDA interoperate, since CUDA is nVidia specific. The CPU only variant should definitely work, but performance will be disappointing since the caffe version caffe_unet bases on is in no way optimized for the CPU.

Did you ever run any GPU-enabled binary based on CUDA in this setup? What's the error you get when running caffe? The fact that caffe throws an error while caffe_unet is showing a usage message might indicate that you have multiple concurrent installations of caffe. This may happen if you install caffe from your package management system and at the same time installing caffe_unet. Check the output of `which caffe` and `which caffe_unet` If one of them points to /usr/bin or the like, you probably have two caffe versions installed and the plugin will fail at least in finetuning mode.

The connection issue may be related to your authentication method. Is there more information than "Connection refused"? Maybe you have to enable legacy protocols in your SSH server. The plugin uses jsch for connection which only support a subset of available SSH protocols.

All the best,

Thorsten

**Comment by ssg5** [comment]
Thanks a lot for your reply, I figured out the problem and proceeded with the CPU variant and the segmentation using the sample data is working. The performance is slow but I think I should be fine. Thanks a lot for your time
.
